<a href="https://colab.research.google.com/github/halimatu001/Data_Science_Assignment/blob/main/Copy_of_Week_2_DSML01_01_FE2383785742.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!pip install numpy
!pip install scikit-learn

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:

file_path = "/content/drive/My Drive/Business Funding Data.csv"

# Try different encodings
df = pd.read_csv(file_path, encoding="ISO-8859-1")  # OR encoding="latin1"

df.head(10)  # Display first few rows



Website Domain             Effective date                   Found At  \
0    trafigura.com                        NaN  2024-03-14T01:00:00+01:00   
1       zenobe.com                        NaN  2024-05-31T02:00:00+02:00   
2       zenobe.com                        NaN  2024-07-24T02:00:00+02:00   
3        canva.com                        NaN  2024-05-01T02:00:00+02:00   
4     fidelity.com                        NaN  2024-04-11T02:00:00+02:00   
5  swtchenergy.com  2024-04-18T02:00:00+02:00  2024-04-24T02:00:00+02:00   
6       carnow.com  2024-04-16T02:00:00+02:00  2024-04-16T02:00:00+02:00   
7   databricks.com                        NaN  2024-08-07T02:00:00+02:00   
8    anthropic.com                        NaN  2024-07-08T02:00:00+02:00   
9           ey.com                        NaN  2024-04-18T02:00:00+02:00   

  Financing Type Financing Type Normalized               Categories  \
0            NaN                       NaN                       []   
1            NaN                       NaN                       []   
2            NaN                       NaN       ["private_equity"]   
3            NaN                       NaN                       []   
4            NaN                       NaN                       []   
5       Series B                  series_b  ["series_b", "venture"]   
6            NaN                       NaN       ["debt_financing"]   
7       Series I                  series_i  ["series_i", "venture"]   
8            NaN                       NaN                       []   
9            NaN                       NaN                       []   

                                           Investors  Investors Count  \
0                                                NaN              NaN   
1  avivainvestors.com, lloydsbankinggroup.com, sa...              9.0   
2                                                NaN              NaN   
3                              stackcapitalgroup.com              1.0   
4                                chevychasetrust.com              1.0   
5                     alantra.com, blueearth.capital              2.0   
6                                   runwaygrowth.com              1.0   
7                                                NaN              NaN   
8                          damachotelsandresorts.com              1.0   
9                                                NaN              NaN   

           Amount  Amount Normalized  \
0           $1.9b         1900000000   
1  $522.7 million          522700000   
2          £41.7m           53671000   
3    US$8 million            8000000   
4   $1.96 million            1960000   
5   $27.2 Million           27200000   
6     $40 million           40000000   
7    $685 million          685000000   
8           $50mn           50000000   
9        AU$10.7M            6865000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...  
5  https://www.mercomindia.com/funding-and-ma-rou...  
6  https://www.prnewswire.com/news-releases/runwa...  
7  https://iteuropa.com/news/large-language-model...  
8  https://www.arabianbusiness.com/industries/tec...  
9  https://www.biometricupdate.com/202404/ey-secu...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Website Domain             26 non-null     object 
 1   Effective date             6 non-null      object 
 2   Found At                   26 non-null     object 
 3   Financing Type             8 non-null      object 
 4   Financing Type Normalized  8 non-null      object 
 5   Categories                 26 non-null     object 
 6   Investors                  13 non-null     object 
 7   Investors Count            13 non-null     float64
 8   Amount                     26 non-null     object 
 9   Amount Normalized          26 non-null     int64  
 10  Source Urls                26 non-null     object 
dtypes: float64(1), int64(1), object(9)
memory usage: 2.4+ KB


### Missing Value

In [ ]:
missing_percentage = df.isnull().sum()/len(df)*100
missing_percentage

Website Domain                0.000000
Effective date               76.923077
Found At                      0.000000
Financing Type               69.230769
Financing Type Normalized    69.230769
Categories                    0.000000
Investors                    50.000000
Investors Count              50.000000
Amount                        0.000000
Amount Normalized             0.000000
Source Urls                   0.000000
dtype: float64

### Find unique value

In [ ]:
df['Effective date'].unique()


array([nan, '2024-04-18T02:00:00+02:00', '2024-04-16T02:00:00+02:00',
       '2024-06-20T02:00:00+02:00', '2024-04-24T02:00:00+02:00',
       '2024-06-26T02:00:00+02:00', '2024-06-27T02:00:00+02:00'],
      dtype=object)

In [ ]:
df['Financing Type'].unique()

array([nan, 'Series B', 'Series I', 'Seed', 'Series A2', 'Series A'],
      dtype=object)

In [ ]:
df['Financing Type Normalized'].unique()

array([nan, 'series_b', 'series_i', 'seed', 'series_a2', 'series_a'],
      dtype=object)

In [ ]:
df['Investors'].unique()

array([nan,
       'avivainvestors.com, lloydsbankinggroup.com, santander.co.uk, swip.com, cibc.com, societegenerale.com, natwest.us, rabobank.com, mufg.jp',
       'stackcapitalgroup.com', 'chevychasetrust.com',
       'alantra.com, blueearth.capital', 'runwaygrowth.com',
       'damachotelsandresorts.com', 'surocap.com', 'eib.org',
       'vistaragrowth.com', 'accelia.vc',
       'edc.ca, desjardinscapital.com, fondsftq.com', 'cibc.com',
       'inovia.vc'], dtype=object)

In [ ]:
df['Investors Count'].unique()

array([nan,  9.,  1.,  2.,  3.])

### Drop Financial Type Normalized Column

In [ ]:
df.drop(columns=['Financing Type Normalized'], inplace=True)

### Drop Amount

In [ ]:
df.drop(columns=['Amount'], inplace=True)

### Drop Investor Count


In [ ]:
df.drop(columns=['Investors Count'], inplace=True)


### Check for info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Website Domain     26 non-null     object
 1   Effective date     26 non-null     object
 2   Found At           26 non-null     object
 3   Financing Type     8 non-null      object
 4   Categories         26 non-null     object
 5   Investors          13 non-null     object
 6   Amount Normalized  26 non-null     int64 
 7   Source Urls        26 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.8+ KB


### Fill in missing value for effective date with mode

In [ ]:
df['Effective date'].fillna(df['Effective date'].mode()[0], inplace=True)


<ipython-input-38-44c04cbf31c1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Effective date'].fillna(df['Effective date'].mode()[0], inplace=True)


### Fill in missing value for financing type with mode

In [ ]:
df['Financing Type'].fillna(df['Financing Type'].mode()[0], inplace=True)


<ipython-input-41-7560fbf873bb>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Financing Type'].fillna(df['Financing Type'].mode()[0], inplace=True)


### Fill in missing value for investor with Unknown

In [ ]:
df['Investors'].fillna("Unknown", inplace=True)


<ipython-input-42-bf7967ae6b5e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Investors'].fillna("Unknown", inplace=True)


### Handling duplicate

In [ ]:
duplicate = df.duplicated().sum()
print(f"Number of duplicated rows: {duplicate}")


Number of duplicated rows: 0


### Removing Outliers

In [ ]:
df.head(10)


Website Domain             Effective date                   Found At  \
0    trafigura.com  2024-04-16T02:00:00+02:00  2024-03-14T01:00:00+01:00   
1       zenobe.com  2024-04-16T02:00:00+02:00  2024-05-31T02:00:00+02:00   
2       zenobe.com  2024-04-16T02:00:00+02:00  2024-07-24T02:00:00+02:00   
3        canva.com  2024-04-16T02:00:00+02:00  2024-05-01T02:00:00+02:00   
4     fidelity.com  2024-04-16T02:00:00+02:00  2024-04-11T02:00:00+02:00   
5  swtchenergy.com  2024-04-18T02:00:00+02:00  2024-04-24T02:00:00+02:00   
6       carnow.com  2024-04-16T02:00:00+02:00  2024-04-16T02:00:00+02:00   
7   databricks.com  2024-04-16T02:00:00+02:00  2024-08-07T02:00:00+02:00   
8    anthropic.com  2024-04-16T02:00:00+02:00  2024-07-08T02:00:00+02:00   
9           ey.com  2024-04-16T02:00:00+02:00  2024-04-18T02:00:00+02:00   

  Financing Type               Categories  \
0           Seed                       []   
1           Seed                       []   
2           Seed       ["private_equity"]   
3           Seed                       []   
4           Seed                       []   
5       Series B  ["series_b", "venture"]   
6           Seed       ["debt_financing"]   
7       Series I  ["series_i", "venture"]   
8           Seed                       []   
9           Seed                       []   

                                           Investors  Amount Normalized  \
0                                            Unknown         1900000000   
1  avivainvestors.com, lloydsbankinggroup.com, sa...          522700000   
2                                            Unknown           53671000   
3                              stackcapitalgroup.com            8000000   
4                                chevychasetrust.com            1960000   
5                     alantra.com, blueearth.capital           27200000   
6                                   runwaygrowth.com           40000000   
7                                            Unknown          685000000   
8                          damachotelsandresorts.com           50000000   
9                                            Unknown            6865000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...  
5  https://www.mercomindia.com/funding-and-ma-rou...  
6  https://www.prnewswire.com/news-releases/runwa...  
7  https://iteuropa.com/news/large-language-model...  
8  https://www.arabianbusiness.com/industries/tec...  
9  https://www.biometricupdate.com/202404/ey-secu...

In [ ]:
mean = df["Amount Normalized"].mean()
std_dev = df["Amount Normalized"].std()

# Calculate Z-score
Z_Score = np.abs((df["Amount Normalized"] - mean) / std_dev)

# Filter outliers (Z-score < 3)
df_no_outliers = df[Z_Score < 3]

# Display the first few rows
df_no_outliers.head()


Website Domain             Effective date                   Found At  \
1       zenobe.com  2024-04-16T02:00:00+02:00  2024-05-31T02:00:00+02:00   
2       zenobe.com  2024-04-16T02:00:00+02:00  2024-07-24T02:00:00+02:00   
3        canva.com  2024-04-16T02:00:00+02:00  2024-05-01T02:00:00+02:00   
4     fidelity.com  2024-04-16T02:00:00+02:00  2024-04-11T02:00:00+02:00   
5  swtchenergy.com  2024-04-18T02:00:00+02:00  2024-04-24T02:00:00+02:00   

  Financing Type               Categories  \
1           Seed                       []   
2           Seed       ["private_equity"]   
3           Seed                       []   
4           Seed                       []   
5       Series B  ["series_b", "venture"]   

                                           Investors  Amount Normalized  \
1  avivainvestors.com, lloydsbankinggroup.com, sa...          522700000   
2                                            Unknown           53671000   
3                              stackcapitalgroup.com            8000000   
4                                chevychasetrust.com            1960000   
5                     alantra.com, blueearth.capital           27200000   

                                         Source Urls  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...  
5  https://www.mercomindia.com/funding-and-ma-rou...

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
categorical_cols = ['Website Domain', 'Financing Type', 'Categories', 'Investors']

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col].astype(str))


In [ ]:
display(df.head())

Website Domain             Effective date                   Found At  \
0  trafigura.com  2024-04-16T02:00:00+02:00  2024-03-14T01:00:00+01:00   
1     zenobe.com  2024-04-16T02:00:00+02:00  2024-05-31T02:00:00+02:00   
2     zenobe.com  2024-04-16T02:00:00+02:00  2024-07-24T02:00:00+02:00   
3      canva.com  2024-04-16T02:00:00+02:00  2024-05-01T02:00:00+02:00   
4   fidelity.com  2024-04-16T02:00:00+02:00  2024-04-11T02:00:00+02:00   

  Financing Type          Categories  \
0           Seed                  []   
1           Seed                  []   
2           Seed  ["private_equity"]   
3           Seed                  []   
4           Seed                  []   

                                           Investors  Amount Normalized  \
0                                            Unknown         1900000000   
1  avivainvestors.com, lloydsbankinggroup.com, sa...          522700000   
2                                            Unknown           53671000   
3                              stackcapitalgroup.com            8000000   
4                                chevychasetrust.com            1960000   

                                         Source Urls  
0  https://www.tradefinanceglobal.com/posts/trafi...  
1  https://realassets.ipe.com/news/aviva-among-le...  
2  https://www.innovationnewsnetwork.com/zenobe-a...  
3  https://www.globenewswire.com/news-release/202...  
4  https://www.defenseworld.net/2024/04/11/chevy-...

In [ ]:
#Save cleaned dataset
df.to_csv('/content/drive/My Drive/Cleaned_Business_Funding_Data.csv', index=False)


### Observations from Exploring the Data
- The dataset contained missing values in 'Effective date', 'Financing Type', 'Investors', and 'Amount Normalized'.
- Some columns ('Financing Type Normalized' and 'Amount') were redundant and removed.
- Duplicates were identified and removed.
- Outliers in 'Amount Normalized' were removed using the Z-score method.

### Steps Taken for Cleaning and Preprocessing
1. **Handled Missing Values:**
   - Used mode for categorical variables (e.g., 'Effective date').
   - Used median for numerical variables ('Amount Normalized').
   
2. **Dropped Redundant Columns:**
   - Removed unnecessary columns that duplicated information.
   
3. **Removed Duplicates:**
   - Ensured unique rows for more accurate analysis.
   
4. **Handled Outliers:**
   - Applied Z-score to remove extreme values.
   
5. **Encoded Categorical Variables:**
   - Used Label Encoding for categorical features.

### Justifications for Each Step
- Mode was used for categorical missing values to maintain consistency.
- Median was chosen for 'Amount Normalized' because it is less affected by extreme values.
- Label Encoding was used for categorical columns to prepare for machine learning models.
- Dropping duplicate and redundant columns made the dataset cleaner and more efficient for analysis.

### Reflections on Data Preprocessing
Data preprocessing is crucial in real-world analysis because raw datasets often contain inconsistencies, missing values, and outliers. Proper cleaning and transformation ensure that analysis and machine learning models provide meaningful insights.
"""
